# Generated by Django 2.1 on 2018-11-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='home_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_card_no',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport_no',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no_2',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertycar',
            name='customer_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyhouse',
            name='customer_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='home_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='id_card_no',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='passport_no',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='phone_no',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='phone_no_2',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wordinfo',
            name='company_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wordinfo',
            name='company_org_no',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wordinfo',
            name='company_phone_no',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wordinfo',
            name='customer_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
