# Generated by Django 2.1 on 2018-12-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20181127_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
