# Generated by Django 2.1 on 2018-12-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20181213_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card_no',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('init', '初始状态'), ('wait_pay', '待付款状态'), ('finish', '完成状态')], db_index=True, default='init', max_length=50),
        ),
    ]
